In [1]:
from pathlib import Path
import xmltodict
import pandas as pd
import numpy as np
import tifffile as tiff
import xmltodict
from dateutil import parser
import re

import matplotlib.pyplot as plt
from collections import namedtuple
from shapely.geometry import box

from skimage.registration import phase_cross_correlation
from skimage.transform import rescale, resize, downscale_local_mean
from skimage import exposure

import zarr
from pylibCZIrw import czi as pyczi

In [ ]:
"""Skip during test
series_folder = Path(r"E:\PROJECTS\EM\LUKE\TA23\Intermediate")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\TA23\Proximal")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\TA23\Distal")
section_folders = []
for folder in series_folder.iterdir():  # Iterate over all items in the folder
    if folder.is_dir() and folder.name.startswith("S_"):
        print(f"fould series folder: {folder.name}")
        section_folders.append(folder)
"""

In [2]:
from atlas.io import is_there_a_single_tif, extract_s_number

In [16]:
series_folder = Path(r"E:\PROJECTS\EM\zeinab\ATLAS-projects\L32-10-2-w2-ROI-20nm-BSD")
series_folder = Path(r"E:\PROJECTS\EM\zeinab\ATLAS-projects\L32-10-1-ROI-w1-20nm-bsd")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\ATLAS-projects\TA31-atlas\Stitched-Sets\TA31-20nm-roi1-2")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\ATLAS-projects\TA31-atlas\Stitched-Sets\TA31-20nm-roi3")
series_folder = Path(r"E:\PROJECTS\EM\zeinab\ATLAS-projects\atlas_olive_2\roi-01-stitched")
series_folder = Path(r"E:\PROJECTS\EM\Filipa\M2-2\Filipa-M2-2-20251127\exports\Tissue-overview-2")
series_folder = Path(r"E:\PROJECTS\EM\Alma\plant-3-wafer-1\alma-plant-3_data\session_422002753\Site 2")
series_folder = Path(r"E:\PROJECTS\EM\Alma\plant4-wafer-1\alma-plant-4_data\session_1084385689\Site 1")
series_folder = Path(r"E:\PROJECTS\EM\Algae Project\Meso\Meso_data\session_1152502930\Site 2")
series_folder = Path(r"E:\PROJECTS\EM\Filipa\M2-2\ATLAS-projects\proj-4-20260302\NEW LOCATION20260303_data\session_1149164643\Site 1")
series_folder = Path(r"E:\PROJECTS\EM\Thomas Gerner\Mice tisssue project_data\session_239138424\Section Set 2")

# Find the first CSV file that starts with "PhaseCC_stitching_S_"
csv_file = next(series_folder.glob("PhaseCC_stitching_S_*.csv"), None)

if csv_file is None:
    raise FileNotFoundError("No matching CSV file found in the folder.")

print(f"Found CSV file: {csv_file.name}")

# Load the CSV into a DataFrame
df = pd.read_csv(csv_file)

# Try to find a 'pixelSize' column or entry
if 'PixelSizeMicron' in df.columns:
    pix_size_micron =  df['PixelSizeMicron'].max()
else:
    raise ValueError("No 'pixelSize' parameter found in the CSV.")

print(f"pixel_size in microns {pix_size_micron}")


#TODO: important change this to metadata readout
pixel_size = {
    'Value': pix_size_micron,
    'Axial': 0.300,
    'Unit': 'µm'
}
print("work on pixel size")
""" EXAMPLE
with open(tif_folder.joinpath('tif-stack-metadata.xml'), "rb") as f:
    metadata_dict = xmltodict.parse(f, xml_attribs=True)

pixel_size = metadata_dict['human_meta_data']['pixel_size']
"""

tif_list = []
for folder in series_folder.iterdir():  # Iterate over all items in the folder
    if folder.is_file() and folder.name.endswith(".tiff"):
        print(f"fould series image: {folder.name}")
        tif_list.append(folder)

Found CSV file: phaseCC_stitching_S_1.csv
pixel_size in microns 0.0149977765977383
work on pixel size
fould series image: stitched_image_S_1.tiff
fould series image: stitched_image_S_10.tiff
fould series image: stitched_image_S_11.tiff
fould series image: stitched_image_S_12.tiff
fould series image: stitched_image_S_13.tiff
fould series image: stitched_image_S_14.tiff
fould series image: stitched_image_S_15.tiff
fould series image: stitched_image_S_16.tiff
fould series image: stitched_image_S_17.tiff
fould series image: stitched_image_S_18.tiff
fould series image: stitched_image_S_19.tiff
fould series image: stitched_image_S_2.tiff
fould series image: stitched_image_S_20.tiff
fould series image: stitched_image_S_21.tiff
fould series image: stitched_image_S_22.tiff
fould series image: stitched_image_S_23.tiff
fould series image: stitched_image_S_24.tiff
fould series image: stitched_image_S_25.tiff
fould series image: stitched_image_S_26.tiff
fould series image: stitched_image_S_27.tiff
fould series image: stitched_image_S_28.tiff
fould series image: stitched_image_S_29.tiff
fould series image: stitched_image_S_3.tiff
fould series image: stitched_image_S_30.tiff
fould series image: stitched_image_S_4.tiff
fould series image: stitched_image_S_5.tiff
fould series image: stitched_image_S_6.tiff
fould series image: stitched_image_S_7.tiff
fould series image: stitched_image_S_8.tiff
fould series image: stitched_image_S_9.tiff

In [17]:
"""SKIP during test
tif_list = []
for section_folder in section_folders:
    single_tif, tif_path = is_there_a_single_tif(section_folder)
    if single_tif:
        #print(tif_path)
        tif_list.append(tif_path)
"""

tif_list_sorted = sorted(tif_list, key=extract_s_number)
from atlas.io import reorder_files_by_s_number, parse_shorthand_order

In [18]:
correct_order_path = Path(series_folder.joinpath("correct_order.txt"))

try:
    new_order = parse_shorthand_order(correct_order_path)
    print(f"Loaded correct_order.txt: {new_order}")

    tif_list_sorted = reorder_files_by_s_number(tif_list_sorted, new_order)
    print("Files reordered based on correct_order.txt:")
    for f in tif_list_sorted:
        print(f)

except FileNotFoundError:
    print("No correct_order.txt found — using original order.")
except Exception as e:
    print(f"Error reading or applying correct_order.txt: {e}")

No correct_order.txt found — using original order.

In [19]:
from atlas.io.fibics_metadata import extract_tif_metadata, get_pixel_size_from_tif
from atlas.io import create_empty_folder, rm_tree, apply_alignment, zarr_array_to_czi
from atlas.image_analysis import image_dtype_min_max, rescale_image_intensity
from atlas.alignment import calculate_cumulative_shifts, initialize_alignment_df, pairwise_alignment, first_last_true, ROI
from atlas.image_analysis import image_dtype_min_max, mask_low_and_saturation, rescale_image_intensity

In [20]:
output_path = series_folder.joinpath("alignment_results")
create_empty_folder(output_path)

down_scale = 10

# initialize the dataframe, in particular we asign the pair-wise patching of the images
# based on the sorted list of tiff.
z_align_df = initialize_alignment_df(tif_list_sorted, down_scale)
# run pairwise alignment based on the provided dataframe
z_align_df = pairwise_alignment(z_align_df)
# now we can calculate the cumulative shifts
z_align_df = calculate_cumulative_shifts(z_align_df)

# ✅ At the end, save the DataFrame as a CSV for later analysis
z_align_df_path = output_path.joinpath("z_alignment_results.pkl")
z_align_df.to_pickle(z_align_df_path)

z_align_df 

#TODO: implement handling of outliers in the alignment results, this can be done by looking at the current shift and then decide whichones looks weird.

Created new (or emptied) folder: E:\PROJECTS\EM\Thomas Gerner\Mice tisssue project_data\session_239138424\Section Set 2\alignment_results
Processing alignment: ref -> stitched_image_S_1.tiff, moving -> stitched_image_S_1.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [0. 0.]
current shift: [0. 0.]
Processing alignment: ref -> stitched_image_S_1.tiff, moving -> stitched_image_S_2.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [90. 83.]
current shift: [90. 83.]
Processing alignment: ref -> stitched_image_S_2.tiff, moving -> stitched_image_S_3.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [120.  28.]
current shift: [120.  28.]
Processing alignment: ref -> stitched_image_S_3.tiff, moving -> stitched_image_S_4.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-95.  -5.]
current shift: [-95.  -5.]
Processing alignment: ref -> stitched_image_S_4.tiff, moving -> stitched_image_S_5.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [113. -86.]
current shift: [113. -86.]
Processing alignment: ref -> stitched_image_S_5.tiff, moving -> stitched_image_S_6.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-16.  -2.]
current shift: [-16.  -2.]
Processing alignment: ref -> stitched_image_S_6.tiff, moving -> stitched_image_S_7.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-134.   49.]
current shift: [-134.   49.]
Processing alignment: ref -> stitched_image_S_7.tiff, moving -> stitched_image_S_8.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-473.  -92.]
current shift: [-473.  -92.]
Processing alignment: ref -> stitched_image_S_8.tiff, moving -> stitched_image_S_9.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [590. 188.]
current shift: [590. 188.]
Processing alignment: ref -> stitched_image_S_9.tiff, moving -> stitched_image_S_10.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [  1. -69.]
current shift: [  1. -69.]
Processing alignment: ref -> stitched_image_S_10.tiff, moving -> stitched_image_S_11.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-67.  -2.]
current shift: [-67.  -2.]
Processing alignment: ref -> stitched_image_S_11.tiff, moving -> stitched_image_S_12.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [249. -13.]
current shift: [249. -13.]
Processing alignment: ref -> stitched_image_S_12.tiff, moving -> stitched_image_S_13.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-158.   46.]
current shift: [-158.   46.]
Processing alignment: ref -> stitched_image_S_13.tiff, moving -> stitched_image_S_14.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [  50. -135.]
current shift: [  50. -135.]
Processing alignment: ref -> stitched_image_S_14.tiff, moving -> stitched_image_S_15.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [156.  19.]
current shift: [156.  19.]
Processing alignment: ref -> stitched_image_S_15.tiff, moving -> stitched_image_S_16.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-120.  129.]
current shift: [-120.  129.]
Processing alignment: ref -> stitched_image_S_16.tiff, moving -> stitched_image_S_17.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-30.  40.]
current shift: [-30.  40.]
Processing alignment: ref -> stitched_image_S_17.tiff, moving -> stitched_image_S_18.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 187. -119.]
current shift: [ 187. -119.]
Processing alignment: ref -> stitched_image_S_18.tiff, moving -> stitched_image_S_19.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-222.  -11.]
current shift: [-222.  -11.]
Processing alignment: ref -> stitched_image_S_19.tiff, moving -> stitched_image_S_20.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [172. 295.]
current shift: [172. 295.]
Processing alignment: ref -> stitched_image_S_20.tiff, moving -> stitched_image_S_21.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-242. -326.]
current shift: [-242. -326.]
Processing alignment: ref -> stitched_image_S_21.tiff, moving -> stitched_image_S_22.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 316. -163.]
current shift: [ 316. -163.]
Processing alignment: ref -> stitched_image_S_22.tiff, moving -> stitched_image_S_23.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-207.  166.]
current shift: [-207.  166.]
Processing alignment: ref -> stitched_image_S_23.tiff, moving -> stitched_image_S_24.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-69. -85.]
current shift: [-69. -85.]
Processing alignment: ref -> stitched_image_S_24.tiff, moving -> stitched_image_S_25.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [159. 396.]
current shift: [159. 396.]
Processing alignment: ref -> stitched_image_S_25.tiff, moving -> stitched_image_S_26.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-57. -24.]
current shift: [-57. -24.]
Processing alignment: ref -> stitched_image_S_26.tiff, moving -> stitched_image_S_27.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ -78. -249.]
current shift: [ -78. -249.]
Processing alignment: ref -> stitched_image_S_27.tiff, moving -> stitched_image_S_28.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-53.  86.]
current shift: [-53.  86.]
Processing alignment: ref -> stitched_image_S_28.tiff, moving -> stitched_image_S_29.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [179.   9.]
current shift: [179.   9.]
Processing alignment: ref -> stitched_image_S_29.tiff, moving -> stitched_image_S_30.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-154.  -69.]
current shift: [-154.  -69.]

,moving_path,reference_path,moving_ROI,reference_ROI,current_shift,cumulative_ROI,cumulative_shift,down_scale
0,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1685, 0, 3759)","(0, 1685, 0, 3759)","[0.0, 0.0]","(0, 1685, 0, 3759)","[0.0, 0.0]",10
1,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1567, 0, 3676)","(0, 1685, 0, 3759)","[90.0, 83.0]","(83, 1650, 90, 3766)","[90.0, 83.0]",10
2,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1507, 0, 3514)","(0, 1567, 0, 3676)","[120.0, 28.0]","(111, 1618, 210, 3724)","[210.0, 111.0]",10
3,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1550, 0, 3816)","(0, 1507, 0, 3514)","[-95.0, -5.0]","(106, 1656, 115, 3931)","[115.0, 106.0]",10
4,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1532, 0, 3737)","(0, 1550, 0, 3816)","[113.0, -86.0]","(20, 1552, 228, 3965)","[228.0, 20.0]",10
5,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1528, 0, 3627)","(0, 1532, 0, 3737)","[-16.0, -2.0]","(18, 1546, 212, 3839)","[212.0, 18.0]",10
6,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1553, 0, 3740)","(0, 1528, 0, 3627)","[-134.0, 49.0]","(67, 1620, 78, 3818)","[78.0, 67.0]",10
7,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1574, 0, 3870)","(0, 1553, 0, 3740)","[-473.0, -92.0]","(-25, 1549, -395, 3475)","[-395.0, -25.0]",10
8,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1544, 0, 3465)","(0, 1574, 0, 3870)","[590.0, 188.0]","(163, 1707, 195, 3660)","[195.0, 163.0]",10
9,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1493, 0, 3738)","(0, 1544, 0, 3465)","[1.0, -69.0]","(94, 1587, 196, 3934)","[196.0, 94.0]",10
10,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1466, 0, 3577)","(0, 1493, 0, 3738)","[-67.0, -2.0]","(92, 1558, 129, 3706)","[129.0, 92.0]",10
11,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1546, 0, 3607)","(0, 1466, 0, 3577)","[249.0, -13.0]","(79, 1625, 378, 3985)","[378.0, 79.0]",10
12,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1482, 0, 3691)","(0, 1546, 0, 3607)","[-158.0, 46.0]","(125, 1607, 220, 3911)","[220.0, 125.0]",10
13,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1535, 0, 3559)","(0, 1482, 0, 3691)","[50.0, -135.0]","(-10, 1525, 270, 3829)","[270.0, -10.0]",10
14,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1512, 0, 3608)","(0, 1535, 0, 3559)","[156.0, 19.0]","(9, 1521, 426, 4034)","[426.0, 9.0]",10
15,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1553, 0, 3647)","(0, 1512, 0, 3608)","[-120.0, 129.0]","(138, 1691, 306, 3953)","[306.0, 138.0]",10
16,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1519, 0, 3773)","(0, 1553, 0, 3647)","[-30.0, 40.0]","(178, 1697, 276, 4049)","[276.0, 178.0]",10
17,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1555, 0, 3648)","(0, 1519, 0, 3773)","[187.0, -119.0]","(59, 1614, 463, 4111)","[463.0, 59.0]",10
18,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1545, 0, 3725)","(0, 1555, 0, 3648)","[-222.0, -11.0]","(48, 1593, 241, 3966)","[241.0, 48.0]",10
19,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1541, 0, 3625)","(0, 1545, 0, 3725)","[172.0, 295.0]","(343, 1884, 413, 4038)","[413.0, 343.0]",10
20,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1531, 0, 3809)","(0, 1541, 0, 3625)","[-242.0, -326.0]","(17, 1548, 171, 3980)","[171.0, 17.0]",10
21,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1487, 0, 3491)","(0, 1531, 0, 3809)","[316.0, -163.0]","(-146, 1341, 487, 3978)","[487.0, -146.0]",10
22,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1547, 0, 3633)","(0, 1487, 0, 3491)","[-207.0, 166.0]","(20, 1567, 280, 3913)","[280.0, 20.0]",10
23,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1549, 0, 3699)","(0, 1547, 0, 3633)","[-69.0, -85.0]","(-65, 1484, 211, 3910)","[211.0, -65.0]",10
24,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1544, 0, 3658)","(0, 1549, 0, 3699)","[159.0, 396.0]","(331, 1875, 370, 4028)","[370.0, 331.0]",10
25,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1455, 0, 3939)","(0, 1544, 0, 3658)","[-57.0, -24.0]","(307, 1762, 313, 4252)","[313.0, 307.0]",10
26,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1571, 0, 3790)","(0, 1455, 0, 3939)","[-78.0, -249.0]","(58, 1629, 235, 4025)","[235.0, 58.0]",10
27,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1528, 0, 3718)","(0, 1571, 0, 3790)","[-53.0, 86.0]","(144, 1672, 182, 3900)","[182.0, 144.0]",10
28,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1506, 0, 3570)","(0, 1528, 0, 3718)","[179.0, 9.0]","(153, 1659, 361, 3931)","[361.0, 153.0]",10
29,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1536, 0, 3830)","(0, 1506, 0, 3570)","[-154.0, -69.0]","(84, 1620, 207, 4037)","[207.0, 84.0]",10

In [21]:
z_align_df = pd.read_pickle(z_align_df_path)
z_align_df

,moving_path,reference_path,moving_ROI,reference_ROI,current_shift,cumulative_ROI,cumulative_shift,down_scale
0,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1685, 0, 3759)","(0, 1685, 0, 3759)","[0.0, 0.0]","(0, 1685, 0, 3759)","[0.0, 0.0]",10
1,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1567, 0, 3676)","(0, 1685, 0, 3759)","[90.0, 83.0]","(83, 1650, 90, 3766)","[90.0, 83.0]",10
2,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1507, 0, 3514)","(0, 1567, 0, 3676)","[120.0, 28.0]","(111, 1618, 210, 3724)","[210.0, 111.0]",10
3,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1550, 0, 3816)","(0, 1507, 0, 3514)","[-95.0, -5.0]","(106, 1656, 115, 3931)","[115.0, 106.0]",10
4,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1532, 0, 3737)","(0, 1550, 0, 3816)","[113.0, -86.0]","(20, 1552, 228, 3965)","[228.0, 20.0]",10
5,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1528, 0, 3627)","(0, 1532, 0, 3737)","[-16.0, -2.0]","(18, 1546, 212, 3839)","[212.0, 18.0]",10
6,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1553, 0, 3740)","(0, 1528, 0, 3627)","[-134.0, 49.0]","(67, 1620, 78, 3818)","[78.0, 67.0]",10
7,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1574, 0, 3870)","(0, 1553, 0, 3740)","[-473.0, -92.0]","(-25, 1549, -395, 3475)","[-395.0, -25.0]",10
8,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1544, 0, 3465)","(0, 1574, 0, 3870)","[590.0, 188.0]","(163, 1707, 195, 3660)","[195.0, 163.0]",10
9,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1493, 0, 3738)","(0, 1544, 0, 3465)","[1.0, -69.0]","(94, 1587, 196, 3934)","[196.0, 94.0]",10
10,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1466, 0, 3577)","(0, 1493, 0, 3738)","[-67.0, -2.0]","(92, 1558, 129, 3706)","[129.0, 92.0]",10
11,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1546, 0, 3607)","(0, 1466, 0, 3577)","[249.0, -13.0]","(79, 1625, 378, 3985)","[378.0, 79.0]",10
12,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1482, 0, 3691)","(0, 1546, 0, 3607)","[-158.0, 46.0]","(125, 1607, 220, 3911)","[220.0, 125.0]",10
13,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1535, 0, 3559)","(0, 1482, 0, 3691)","[50.0, -135.0]","(-10, 1525, 270, 3829)","[270.0, -10.0]",10
14,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1512, 0, 3608)","(0, 1535, 0, 3559)","[156.0, 19.0]","(9, 1521, 426, 4034)","[426.0, 9.0]",10
15,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1553, 0, 3647)","(0, 1512, 0, 3608)","[-120.0, 129.0]","(138, 1691, 306, 3953)","[306.0, 138.0]",10
16,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1519, 0, 3773)","(0, 1553, 0, 3647)","[-30.0, 40.0]","(178, 1697, 276, 4049)","[276.0, 178.0]",10
17,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1555, 0, 3648)","(0, 1519, 0, 3773)","[187.0, -119.0]","(59, 1614, 463, 4111)","[463.0, 59.0]",10
18,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1545, 0, 3725)","(0, 1555, 0, 3648)","[-222.0, -11.0]","(48, 1593, 241, 3966)","[241.0, 48.0]",10
19,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1541, 0, 3625)","(0, 1545, 0, 3725)","[172.0, 295.0]","(343, 1884, 413, 4038)","[413.0, 343.0]",10
20,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1531, 0, 3809)","(0, 1541, 0, 3625)","[-242.0, -326.0]","(17, 1548, 171, 3980)","[171.0, 17.0]",10
21,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1487, 0, 3491)","(0, 1531, 0, 3809)","[316.0, -163.0]","(-146, 1341, 487, 3978)","[487.0, -146.0]",10
22,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1547, 0, 3633)","(0, 1487, 0, 3491)","[-207.0, 166.0]","(20, 1567, 280, 3913)","[280.0, 20.0]",10
23,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1549, 0, 3699)","(0, 1547, 0, 3633)","[-69.0, -85.0]","(-65, 1484, 211, 3910)","[211.0, -65.0]",10
24,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1544, 0, 3658)","(0, 1549, 0, 3699)","[159.0, 396.0]","(331, 1875, 370, 4028)","[370.0, 331.0]",10
25,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1455, 0, 3939)","(0, 1544, 0, 3658)","[-57.0, -24.0]","(307, 1762, 313, 4252)","[313.0, 307.0]",10
26,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1571, 0, 3790)","(0, 1455, 0, 3939)","[-78.0, -249.0]","(58, 1629, 235, 4025)","[235.0, 58.0]",10
27,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1528, 0, 3718)","(0, 1571, 0, 3790)","[-53.0, 86.0]","(144, 1672, 182, 3900)","[182.0, 144.0]",10
28,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1506, 0, 3570)","(0, 1528, 0, 3718)","[179.0, 9.0]","(153, 1659, 361, 3931)","[361.0, 153.0]",10
29,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,E:\PROJECTS\EM\Thomas Gerner\Mice tisssue proj...,"(0, 1536, 0, 3830)","(0, 1506, 0, 3570)","[-154.0, -69.0]","(84, 1620, 207, 4037)","[207.0, 84.0]",10

In [22]:
use_down_sample = True
zarr_array, zarr_path = apply_alignment(z_align_df, buffer_pixels=20, percentile_low=2.0, percentile_high=99.5, use_down_sample=use_down_sample)

out_pixel_size = pixel_size.copy()

if use_down_sample:
    out_pixel_size['Value'] = pixel_size['Value'] * down_scale
    end_str = "_ds_aligned"
else:
    end_str = "_aligned"

czi_path = zarr_array_to_czi(zarr_path, out_pixel_size, end_str=end_str)

we will downsample during saving of the zarr, this is good during testing for visual inspection
shape of the zarr array to create: (4687, 2070, 30)
creating zarr at: E:\PROJECTS\EM\Thomas Gerner\Mice tisssue project_data\session_239138424\Section Set 2\Section Set 2.zarr
Done for idx 0
Done for idx 1
Done for idx 2
Done for idx 3
Done for idx 4
Done for idx 5
Done for idx 6
Done for idx 7
Done for idx 8
Done for idx 9
Done for idx 10
Done for idx 11
Done for idx 12
Done for idx 13
Done for idx 14
Done for idx 15
Done for idx 16
Done for idx 17
Done for idx 18
Done for idx 19
Done for idx 20
Done for idx 21
Done for idx 22
Done for idx 23
Done for idx 24
Done for idx 25
Done for idx 26
Done for idx 27
Done for idx 28
Done for idx 29
Saving CZI file to: E:\PROJECTS\EM\Thomas Gerner\Mice tisssue project_data\session_239138424\Section Set 2\Section Set 2_ds_aligned.czi
Processing frame 0
Processing frame 1
Processing frame 2
Processing frame 3
Processing frame 4
Processing frame 5
Processing frame 6
Processing frame 7
Processing frame 8
Processing frame 9
Processing frame 10
Processing frame 11
Processing frame 12
Processing frame 13
Processing frame 14
Processing frame 15
Processing frame 16
Processing frame 17
Processing frame 18
Processing frame 19
Processing frame 20
Processing frame 21
Processing frame 22
Processing frame 23
Processing frame 24
Processing frame 25
Processing frame 26
Processing frame 27
Processing frame 28
Processing frame 29

In [23]:
if zarr_path.exists():
  rm_tree(zarr_path)

In [24]:
use_down_sample = False
zarr_array, zarr_path = apply_alignment(z_align_df, buffer_pixels=1, percentile_low=2.0, percentile_high=99.8, use_down_sample=use_down_sample)

doing full scale alignment, it is recomended to check results before with downscale
shape of the zarr array to create: (46472, 20302, 30)
creating zarr at: E:\PROJECTS\EM\Thomas Gerner\Mice tisssue project_data\session_239138424\Section Set 2\Section Set 2.zarr
Done for idx 0
Done for idx 1
Done for idx 2
Done for idx 3
Done for idx 4
Done for idx 5
Done for idx 6
Done for idx 7
Done for idx 8
Done for idx 9
Done for idx 10
Done for idx 11
Done for idx 12
Done for idx 13
Done for idx 14
Done for idx 15
Done for idx 16
Done for idx 17
Done for idx 18
Done for idx 19
Done for idx 20
Done for idx 21
Done for idx 22
Done for idx 23
Done for idx 24
Done for idx 25
Done for idx 26
Done for idx 27
Done for idx 28
Done for idx 29

In [25]:
out_pixel_size = pixel_size.copy()

if use_down_sample:
    out_pixel_size['Value'] = pixel_size['Value'] * down_scale
    end_str = "_ds_aligned"
else:
    end_str = "_aligned"

czi_path = zarr_array_to_czi(zarr_path, out_pixel_size, end_str=end_str)

Saving CZI file to: E:\PROJECTS\EM\Thomas Gerner\Mice tisssue project_data\session_239138424\Section Set 2\Section Set 2_aligned.czi
Processing frame 0
Processing frame 1
Processing frame 2
Processing frame 3
Processing frame 4
Processing frame 5
Processing frame 6
Processing frame 7
Processing frame 8
Processing frame 9
Processing frame 10
Processing frame 11
Processing frame 12
Processing frame 13
Processing frame 14
Processing frame 15
Processing frame 16
Processing frame 17
Processing frame 18
Processing frame 19
Processing frame 20
Processing frame 21
Processing frame 22
Processing frame 23
Processing frame 24
Processing frame 25
Processing frame 26
Processing frame 27
Processing frame 28
Processing frame 29