In [1]:
from pathlib import Path
import xmltodict
import pandas as pd
import numpy as np
import tifffile as tiff
import xmltodict
from dateutil import parser
import re

import matplotlib.pyplot as plt
from collections import namedtuple
from shapely.geometry import box

from skimage.registration import phase_cross_correlation
from skimage.transform import rescale, resize, downscale_local_mean
from skimage import exposure

import zarr
from pylibCZIrw import czi as pyczi

In [2]:
"""Skip during test
series_folder = Path(r"E:\PROJECTS\EM\LUKE\TA23\Intermediate")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\TA23\Proximal")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\TA23\Distal")
section_folders = []
for folder in series_folder.iterdir():  # Iterate over all items in the folder
    if folder.is_dir() and folder.name.startswith("S_"):
        print(f"fould series folder: {folder.name}")
        section_folders.append(folder)
"""

'Skip during test\nseries_folder = Path(r"E:\\PROJECTS\\EM\\LUKE\\TA23\\Intermediate")\nseries_folder = Path(r"E:\\PROJECTS\\EM\\LUKE\\TA23\\Proximal")\nseries_folder = Path(r"E:\\PROJECTS\\EM\\LUKE\\TA23\\Distal")\nsection_folders = []\nfor folder in series_folder.iterdir():  # Iterate over all items in the folder\n    if folder.is_dir() and folder.name.startswith("S_"):\n        print(f"fould series folder: {folder.name}")\n        section_folders.append(folder)\n'

In [3]:
from atlas.io import is_there_a_single_tif, extract_s_number

In [4]:
series_folder = Path(r"E:\PROJECTS\EM\zeinab\ATLAS-projects\L32-10-2-w2-ROI-20nm-BSD")
series_folder = Path(r"E:\PROJECTS\EM\zeinab\ATLAS-projects\L32-10-1-ROI-w1-20nm-bsd")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\ATLAS-projects\TA31-atlas\Stitched-Sets\TA31-20nm-roi1-2")
series_folder = Path(r"E:\PROJECTS\EM\LUKE\ATLAS-projects\TA31-atlas\Stitched-Sets\TA31-20nm-roi3")
series_folder = Path(r"E:\PROJECTS\EM\zeinab\ATLAS-projects\atlas_olive_2\roi-01-stitched")
series_folder = Path(r"E:\PROJECTS\EM\Filipa\M2-2\Filipa-M2-2-20251127\exports\Tissue-overview-2")
series_folder = Path(r"E:\PROJECTS\EM\Alma\plant-3-wafer-1\alma-plant-3_data\session_422002753\Site 2")
series_folder = Path(r"E:\PROJECTS\EM\Alma\plant4-wafer-1\alma-plant-4_data\session_1084385689\Site 1")
series_folder = Path(r"E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_data\session_1115605826\Site 2")
#series_folder = Path(r"E:\PROJECTS\EM\Alma\test")

# Find the first CSV file that starts with "PhaseCC_stitching_S_"
csv_file = next(series_folder.glob("PhaseCC_stitching_S_*.csv"), None)

if csv_file is None:
    raise FileNotFoundError("No matching CSV file found in the folder.")

print(f"Found CSV file: {csv_file.name}")

# Load the CSV into a DataFrame
df = pd.read_csv(csv_file)

# Try to find a 'pixelSize' column or entry
if 'PixelSizeMicron' in df.columns:
    pix_size_micron =  df['PixelSizeMicron'].max()
else:
    raise ValueError("No 'pixelSize' parameter found in the CSV.")

print(f"pixel_size in microns {pix_size_micron}")


#TODO: important change this to metadata readout
pixel_size = {
    'Value': pix_size_micron,
    'Axial': 0.200,
    'Unit': 'µm'
}
print("work on pixel size")
""" EXAMPLE
with open(tif_folder.joinpath('tif-stack-metadata.xml'), "rb") as f:
    metadata_dict = xmltodict.parse(f, xml_attribs=True)

pixel_size = metadata_dict['human_meta_data']['pixel_size']
"""

tif_list = []
for folder in series_folder.iterdir():  # Iterate over all items in the folder
    if folder.is_file() and folder.name.endswith(".tiff"):
        print(f"fould series image: {folder.name}")
        tif_list.append(folder)

Found CSV file: phaseCC_stitching_S_1.csv
pixel_size in microns 0.0200251038444286
work on pixel size
fould series image: stitched_image_S_1.tiff
fould series image: stitched_image_S_10.tiff
fould series image: stitched_image_S_100.tiff
fould series image: stitched_image_S_101.tiff
fould series image: stitched_image_S_102.tiff
fould series image: stitched_image_S_103.tiff
fould series image: stitched_image_S_104.tiff
fould series image: stitched_image_S_105.tiff
fould series image: stitched_image_S_106.tiff
fould series image: stitched_image_S_107.tiff
fould series image: stitched_image_S_108.tiff
fould series image: stitched_image_S_109.tiff
fould series image: stitched_image_S_11.tiff
fould series image: stitched_image_S_110.tiff
fould series image: stitched_image_S_111.tiff
fould series image: stitched_image_S_112.tiff
fould series image: stitched_image_S_113.tiff
fould series image: stitched_image_S_114.tiff
fould series image: stitched_image_S_115.tiff
fould series image: stitched_image_S_116.tiff
fould series image: stitched_image_S_117.tiff
fould series image: stitched_image_S_118.tiff
fould series image: stitched_image_S_12.tiff
fould series image: stitched_image_S_13.tiff
fould series image: stitched_image_S_14.tiff
fould series image: stitched_image_S_15.tiff
fould series image: stitched_image_S_16.tiff
fould series image: stitched_image_S_17.tiff
fould series image: stitched_image_S_18.tiff
fould series image: stitched_image_S_19.tiff
fould series image: stitched_image_S_2.tiff
fould series image: stitched_image_S_20.tiff
fould series image: stitched_image_S_21.tiff
fould series image: stitched_image_S_22.tiff
fould series image: stitched_image_S_23.tiff
fould series image: stitched_image_S_24.tiff
fould series image: stitched_image_S_25.tiff
fould series image: stitched_image_S_26.tiff
fould series image: stitched_image_S_28.tiff
fould series image: stitched_image_S_29.tiff
fould series image: stitched_image_S_3.tiff
fould series image: stitched_image_S_30.tiff
fould series image: stitched_image_S_31.tiff
fould series image: stitched_image_S_32.tiff
fould series image: stitched_image_S_33.tiff
fould series image: stitched_image_S_34.tiff
fould series image: stitched_image_S_35.tiff
fould series image: stitched_image_S_36.tiff
fould series image: stitched_image_S_37.tiff
fould series image: stitched_image_S_38.tiff
fould series image: stitched_image_S_39.tiff
fould series image: stitched_image_S_4.tiff
fould series image: stitched_image_S_40.tiff
fould series image: stitched_image_S_41.tiff
fould series image: stitched_image_S_42.tiff
fould series image: stitched_image_S_43.tiff
fould series image: stitched_image_S_45.tiff
fould series image: stitched_image_S_46.tiff
fould series image: stitched_image_S_47.tiff
fould series image: stitched_image_S_48.tiff
fould series image: stitched_image_S_49.tiff
fould series image: stitched_image_S_5.tiff
fould series image: stitched_image_S_50.tiff
fould series image: stitched_image_S_51.tiff
fould series image: stitched_image_S_52.tiff
fould series image: stitched_image_S_53.tiff
fould series image: stitched_image_S_54.tiff
fould series image: stitched_image_S_55.tiff
fould series image: stitched_image_S_56.tiff
fould series image: stitched_image_S_57.tiff
fould series image: stitched_image_S_58.tiff
fould series image: stitched_image_S_59.tiff
fould series image: stitched_image_S_6.tiff
fould series image: stitched_image_S_60.tiff
fould series image: stitched_image_S_61.tiff
fould series image: stitched_image_S_62.tiff
fould series image: stitched_image_S_63.tiff
fould series image: stitched_image_S_64.tiff
fould series image: stitched_image_S_65.tiff
fould series image: stitched_image_S_66.tiff
fould series image: stitched_image_S_67.tiff
fould series image: stitched_image_S_68.tiff
fould series image: stitched_image_S_69.tiff
fould series image: stitched_image_S_7.tiff
fould series image: stitched_image_S_70.tiff
fould series image: stitched_image_S_71.tiff
fould series image: stitched_image_S_72.tiff
fould series image: stitched_image_S_73.tiff
fould series image: stitched_image_S_74.tiff
fould series image: stitched_image_S_75.tiff
fould series image: stitched_image_S_76.tiff
fould series image: stitched_image_S_77.tiff
fould series image: stitched_image_S_78.tiff
fould series image: stitched_image_S_79.tiff
fould series image: stitched_image_S_8.tiff
fould series image: stitched_image_S_80.tiff
fould series image: stitched_image_S_81.tiff
fould series image: stitched_image_S_82.tiff
fould series image: stitched_image_S_83.tiff
fould series image: stitched_image_S_84.tiff
fould series image: stitched_image_S_85.tiff
fould series image: stitched_image_S_86.tiff
fould series image: stitched_image_S_87.tiff
fould series image: stitched_image_S_88.tiff
fould series image: stitched_image_S_89.tiff
fould series image: stitched_image_S_9.tiff
fould series image: stitched_image_S_90.tiff
fould series image: stitched_image_S_91.tiff
fould series image: stitched_image_S_92.tiff
fould series image: stitched_image_S_93.tiff
fould series image: stitched_image_S_94.tiff
fould series image: stitched_image_S_95.tiff
fould series image: stitched_image_S_96.tiff
fould series image: stitched_image_S_97.tiff
fould series image: stitched_image_S_98.tiff
fould series image: stitched_image_S_99.tiff

In [5]:
"""SKIP during test
tif_list = []
for section_folder in section_folders:
    single_tif, tif_path = is_there_a_single_tif(section_folder)
    if single_tif:
        #print(tif_path)
        tif_list.append(tif_path)
"""

tif_list_sorted = sorted(tif_list, key=extract_s_number)
from atlas.io import reorder_files_by_s_number, parse_shorthand_order

In [6]:
correct_order_path = Path(series_folder.joinpath("correct_order.txt"))

try:
    new_order = parse_shorthand_order(correct_order_path)
    print(f"Loaded correct_order.txt: {new_order}")

    tif_list_sorted = reorder_files_by_s_number(tif_list_sorted, new_order)
    print("Files reordered based on correct_order.txt:")
    for f in tif_list_sorted:
        print(f)

except FileNotFoundError:
    print("No correct_order.txt found — using original order.")
except Exception as e:
    print(f"Error reading or applying correct_order.txt: {e}")

No correct_order.txt found — using original order.

In [7]:
from atlas.io.fibics_metadata import extract_tif_metadata, get_pixel_size_from_tif
from atlas.io import create_empty_folder, rm_tree, apply_alignment, zarr_array_to_czi
from atlas.image_analysis import image_dtype_min_max, rescale_image_intensity
from atlas.alignment import calculate_cumulative_shifts, initialize_alignment_df, pairwise_alignment, first_last_true, ROI
from atlas.image_analysis import image_dtype_min_max, mask_low_and_saturation, rescale_image_intensity

In [8]:
output_path = series_folder.joinpath("alignment_results")
create_empty_folder(output_path)

down_scale = 10

# initialize the dataframe, in particular we asign the pair-wise patching of the images
# based on the sorted list of tiff.
z_align_df = initialize_alignment_df(tif_list_sorted, down_scale)
# run pairwise alignment based on the provided dataframe
z_align_df = pairwise_alignment(z_align_df)
# now we can calculate the cumulative shifts
z_align_df = calculate_cumulative_shifts(z_align_df)

# ✅ At the end, save the DataFrame as a CSV for later analysis
z_align_df_path = output_path.joinpath("z_alignment_results.pkl")
z_align_df.to_pickle(z_align_df_path)

z_align_df 

#TODO: implement handling of outliers in the alignment results, this can be done by looking at the current shift and then decide whichones looks weird.

Created new (or emptied) folder: E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_data\session_1115605826\Site 2\alignment_results
Processing alignment: ref -> stitched_image_S_1.tiff, moving -> stitched_image_S_1.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [0. 0.]
current shift: [0. 0.]
Processing alignment: ref -> stitched_image_S_1.tiff, moving -> stitched_image_S_2.tiff
crop pixel shift: [0 5]
Detected pixel offset based on crops (row, col): [-5. 13.]
current shift: [-5. 18.]
Processing alignment: ref -> stitched_image_S_2.tiff, moving -> stitched_image_S_3.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ -3. -12.]
current shift: [ -3. -12.]
Processing alignment: ref -> stitched_image_S_3.tiff, moving -> stitched_image_S_4.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-3.  0.]
current shift: [-3.  0.]
Processing alignment: ref -> stitched_image_S_4.tiff, moving -> stitched_image_S_5.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [14.  6.]
current shift: [14.  6.]
Processing alignment: ref -> stitched_image_S_5.tiff, moving -> stitched_image_S_6.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-9. -6.]
current shift: [-9. -6.]
Processing alignment: ref -> stitched_image_S_6.tiff, moving -> stitched_image_S_7.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [14. -9.]
current shift: [14. -9.]
Processing alignment: ref -> stitched_image_S_7.tiff, moving -> stitched_image_S_8.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-36.  18.]
current shift: [-36.  18.]
Processing alignment: ref -> stitched_image_S_8.tiff, moving -> stitched_image_S_9.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [14.  2.]
current shift: [14.  2.]
Processing alignment: ref -> stitched_image_S_9.tiff, moving -> stitched_image_S_10.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [  4. -12.]
current shift: [  4. -12.]
Processing alignment: ref -> stitched_image_S_10.tiff, moving -> stitched_image_S_11.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [12.  1.]
current shift: [12.  1.]
Processing alignment: ref -> stitched_image_S_11.tiff, moving -> stitched_image_S_12.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [1. 1.]
current shift: [1. 1.]
Processing alignment: ref -> stitched_image_S_12.tiff, moving -> stitched_image_S_13.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-17.  -1.]
current shift: [-17.  -1.]
Processing alignment: ref -> stitched_image_S_13.tiff, moving -> stitched_image_S_14.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [14.  9.]
current shift: [14.  9.]
Processing alignment: ref -> stitched_image_S_14.tiff, moving -> stitched_image_S_15.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-32. -10.]
current shift: [-32. -10.]
Processing alignment: ref -> stitched_image_S_15.tiff, moving -> stitched_image_S_16.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [21.  9.]
current shift: [21.  9.]
Processing alignment: ref -> stitched_image_S_16.tiff, moving -> stitched_image_S_17.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [31.  7.]
current shift: [31.  7.]
Processing alignment: ref -> stitched_image_S_17.tiff, moving -> stitched_image_S_18.tiff
crop pixel shift: [1 2]
Detected pixel offset based on crops (row, col): [-56.  14.]
current shift: [-55.  16.]
Processing alignment: ref -> stitched_image_S_18.tiff, moving -> stitched_image_S_19.tiff
crop pixel shift: [-2  0]
Detected pixel offset based on crops (row, col): [50. -8.]
current shift: [48. -8.]
Processing alignment: ref -> stitched_image_S_19.tiff, moving -> stitched_image_S_20.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-7. 20.]
current shift: [-7. 20.]
Processing alignment: ref -> stitched_image_S_20.tiff, moving -> stitched_image_S_21.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-5. -5.]
current shift: [-5. -5.]
Processing alignment: ref -> stitched_image_S_21.tiff, moving -> stitched_image_S_22.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-8. -3.]
current shift: [-8. -3.]
Processing alignment: ref -> stitched_image_S_22.tiff, moving -> stitched_image_S_23.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [25. 10.]
current shift: [25. 10.]
Processing alignment: ref -> stitched_image_S_23.tiff, moving -> stitched_image_S_24.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ -5. -15.]
current shift: [ -5. -15.]
Processing alignment: ref -> stitched_image_S_24.tiff, moving -> stitched_image_S_25.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [0. 0.]
current shift: [0. 0.]
Processing alignment: ref -> stitched_image_S_25.tiff, moving -> stitched_image_S_26.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [16.  5.]
current shift: [16.  5.]
Processing alignment: ref -> stitched_image_S_26.tiff, moving -> stitched_image_S_28.tiff
crop pixel shift: [-1  3]
Detected pixel offset based on crops (row, col): [-43.  13.]
current shift: [-44.  16.]
Processing alignment: ref -> stitched_image_S_28.tiff, moving -> stitched_image_S_29.tiff
crop pixel shift: [1 0]
Detected pixel offset based on crops (row, col): [ -7. -11.]
current shift: [ -6. -11.]
Processing alignment: ref -> stitched_image_S_29.tiff, moving -> stitched_image_S_30.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-10.   4.]
current shift: [-10.   4.]
Processing alignment: ref -> stitched_image_S_30.tiff, moving -> stitched_image_S_31.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [37.  4.]
current shift: [37.  4.]
Processing alignment: ref -> stitched_image_S_31.tiff, moving -> stitched_image_S_32.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ -8. -14.]
current shift: [ -8. -14.]
Processing alignment: ref -> stitched_image_S_32.tiff, moving -> stitched_image_S_33.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-12.   7.]
current shift: [-12.   7.]
Processing alignment: ref -> stitched_image_S_33.tiff, moving -> stitched_image_S_34.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [2. 5.]
current shift: [2. 5.]
Processing alignment: ref -> stitched_image_S_34.tiff, moving -> stitched_image_S_35.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [4. 0.]
current shift: [4. 0.]
Processing alignment: ref -> stitched_image_S_35.tiff, moving -> stitched_image_S_36.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-21.  -8.]
current shift: [-21.  -8.]
Processing alignment: ref -> stitched_image_S_36.tiff, moving -> stitched_image_S_37.tiff
crop pixel shift: [ 0 -2]
Detected pixel offset based on crops (row, col): [31. -4.]
current shift: [31. -6.]
Processing alignment: ref -> stitched_image_S_37.tiff, moving -> stitched_image_S_38.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-6.  3.]
current shift: [-6.  3.]
Processing alignment: ref -> stitched_image_S_38.tiff, moving -> stitched_image_S_39.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 7. -4.]
current shift: [ 7. -4.]
Processing alignment: ref -> stitched_image_S_39.tiff, moving -> stitched_image_S_40.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-10.   4.]
current shift: [-10.   4.]
Processing alignment: ref -> stitched_image_S_40.tiff, moving -> stitched_image_S_41.tiff
crop pixel shift: [-1  0]
Detected pixel offset based on crops (row, col): [-5.  0.]
current shift: [-6.  0.]
Processing alignment: ref -> stitched_image_S_41.tiff, moving -> stitched_image_S_42.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 7. -7.]
current shift: [ 7. -7.]
Processing alignment: ref -> stitched_image_S_42.tiff, moving -> stitched_image_S_43.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [2. 5.]
current shift: [2. 5.]
Processing alignment: ref -> stitched_image_S_43.tiff, moving -> stitched_image_S_45.tiff
crop pixel shift: [1 0]
Detected pixel offset based on crops (row, col): [21. 14.]
current shift: [22. 14.]
Processing alignment: ref -> stitched_image_S_45.tiff, moving -> stitched_image_S_46.tiff
crop pixel shift: [-1  2]
Detected pixel offset based on crops (row, col): [-2. 10.]
current shift: [-3. 12.]
Processing alignment: ref -> stitched_image_S_46.tiff, moving -> stitched_image_S_47.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [11.  6.]
current shift: [11.  6.]
Processing alignment: ref -> stitched_image_S_47.tiff, moving -> stitched_image_S_48.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-21. -18.]
current shift: [-21. -18.]
Processing alignment: ref -> stitched_image_S_48.tiff, moving -> stitched_image_S_49.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-4.  4.]
current shift: [-4.  4.]
Processing alignment: ref -> stitched_image_S_49.tiff, moving -> stitched_image_S_50.tiff
crop pixel shift: [ 1 -3]
Detected pixel offset based on crops (row, col): [-10. -47.]
current shift: [ -9. -50.]
Processing alignment: ref -> stitched_image_S_50.tiff, moving -> stitched_image_S_51.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [22.  3.]
current shift: [22.  3.]
Processing alignment: ref -> stitched_image_S_51.tiff, moving -> stitched_image_S_52.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [  6. -23.]
current shift: [  6. -23.]
Processing alignment: ref -> stitched_image_S_52.tiff, moving -> stitched_image_S_53.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-33.  27.]
current shift: [-33.  27.]
Processing alignment: ref -> stitched_image_S_53.tiff, moving -> stitched_image_S_54.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [0. 0.]
current shift: [0. 0.]
Processing alignment: ref -> stitched_image_S_54.tiff, moving -> stitched_image_S_55.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [21. -4.]
current shift: [21. -4.]
Processing alignment: ref -> stitched_image_S_55.tiff, moving -> stitched_image_S_56.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-13.   5.]
current shift: [-13.   5.]
Processing alignment: ref -> stitched_image_S_56.tiff, moving -> stitched_image_S_57.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [17.  2.]
current shift: [17.  2.]
Processing alignment: ref -> stitched_image_S_57.tiff, moving -> stitched_image_S_58.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 6. 14.]
current shift: [ 6. 14.]
Processing alignment: ref -> stitched_image_S_58.tiff, moving -> stitched_image_S_59.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-21.  -3.]
current shift: [-21.  -3.]
Processing alignment: ref -> stitched_image_S_59.tiff, moving -> stitched_image_S_60.tiff
crop pixel shift: [-1 -2]
Detected pixel offset based on crops (row, col): [-16. -36.]
current shift: [-17. -38.]
Processing alignment: ref -> stitched_image_S_60.tiff, moving -> stitched_image_S_61.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 25. -12.]
current shift: [ 25. -12.]
Processing alignment: ref -> stitched_image_S_61.tiff, moving -> stitched_image_S_62.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [5. 5.]
current shift: [5. 5.]
Processing alignment: ref -> stitched_image_S_62.tiff, moving -> stitched_image_S_63.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-7. -3.]
current shift: [-7. -3.]
Processing alignment: ref -> stitched_image_S_63.tiff, moving -> stitched_image_S_64.tiff
crop pixel shift: [2 0]
Detected pixel offset based on crops (row, col): [38. -1.]
current shift: [40. -1.]
Processing alignment: ref -> stitched_image_S_64.tiff, moving -> stitched_image_S_65.tiff
crop pixel shift: [-2  3]
Detected pixel offset based on crops (row, col): [-16.  24.]
current shift: [-18.  27.]
Processing alignment: ref -> stitched_image_S_65.tiff, moving -> stitched_image_S_66.tiff
crop pixel shift: [1 0]
Detected pixel offset based on crops (row, col): [30. 25.]
current shift: [31. 25.]
Processing alignment: ref -> stitched_image_S_66.tiff, moving -> stitched_image_S_67.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [7. 4.]
current shift: [7. 4.]
Processing alignment: ref -> stitched_image_S_67.tiff, moving -> stitched_image_S_68.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [13.  5.]
current shift: [13.  5.]
Processing alignment: ref -> stitched_image_S_68.tiff, moving -> stitched_image_S_69.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-41.  -1.]
current shift: [-41.  -1.]
Processing alignment: ref -> stitched_image_S_69.tiff, moving -> stitched_image_S_70.tiff
crop pixel shift: [-1 -5]
Detected pixel offset based on crops (row, col): [-34. -40.]
current shift: [-35. -45.]
Processing alignment: ref -> stitched_image_S_70.tiff, moving -> stitched_image_S_71.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [16.  0.]
current shift: [16.  0.]
Processing alignment: ref -> stitched_image_S_71.tiff, moving -> stitched_image_S_72.tiff
crop pixel shift: [0 2]
Detected pixel offset based on crops (row, col): [-1. -7.]
current shift: [-1. -5.]
Processing alignment: ref -> stitched_image_S_72.tiff, moving -> stitched_image_S_73.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [7. 2.]
current shift: [7. 2.]
Processing alignment: ref -> stitched_image_S_73.tiff, moving -> stitched_image_S_74.tiff
crop pixel shift: [ 0 -2]
Detected pixel offset based on crops (row, col): [17.  2.]
current shift: [17.  0.]
Processing alignment: ref -> stitched_image_S_74.tiff, moving -> stitched_image_S_75.tiff
crop pixel shift: [0 2]
Detected pixel offset based on crops (row, col): [-10. -12.]
current shift: [-10. -10.]
Processing alignment: ref -> stitched_image_S_75.tiff, moving -> stitched_image_S_76.tiff
crop pixel shift: [ 2 -2]
Detected pixel offset based on crops (row, col): [-19.  13.]
current shift: [-17.  11.]
Processing alignment: ref -> stitched_image_S_76.tiff, moving -> stitched_image_S_77.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [33. -7.]
current shift: [33. -7.]
Processing alignment: ref -> stitched_image_S_77.tiff, moving -> stitched_image_S_78.tiff
crop pixel shift: [1 5]
Detected pixel offset based on crops (row, col): [-13.  31.]
current shift: [-12.  36.]
Processing alignment: ref -> stitched_image_S_78.tiff, moving -> stitched_image_S_79.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [29. -4.]
current shift: [29. -4.]
Processing alignment: ref -> stitched_image_S_79.tiff, moving -> stitched_image_S_80.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-23.  13.]
current shift: [-23.  13.]
Processing alignment: ref -> stitched_image_S_80.tiff, moving -> stitched_image_S_81.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 19. -10.]
current shift: [ 19. -10.]
Processing alignment: ref -> stitched_image_S_81.tiff, moving -> stitched_image_S_82.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [11.  5.]
current shift: [11.  5.]
Processing alignment: ref -> stitched_image_S_82.tiff, moving -> stitched_image_S_83.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-9. -8.]
current shift: [-9. -8.]
Processing alignment: ref -> stitched_image_S_83.tiff, moving -> stitched_image_S_84.tiff
crop pixel shift: [-2  0]
Detected pixel offset based on crops (row, col): [-37.  -9.]
current shift: [-39.  -9.]
Processing alignment: ref -> stitched_image_S_84.tiff, moving -> stitched_image_S_85.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [15.  0.]
current shift: [15.  0.]
Processing alignment: ref -> stitched_image_S_85.tiff, moving -> stitched_image_S_86.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [5. 0.]
current shift: [5. 0.]
Processing alignment: ref -> stitched_image_S_86.tiff, moving -> stitched_image_S_87.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-1.  9.]
current shift: [-1.  9.]
Processing alignment: ref -> stitched_image_S_87.tiff, moving -> stitched_image_S_88.tiff
crop pixel shift: [-1  0]
Detected pixel offset based on crops (row, col): [ 29. -14.]
current shift: [ 28. -14.]
Processing alignment: ref -> stitched_image_S_88.tiff, moving -> stitched_image_S_89.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-59.  23.]
current shift: [-59.  23.]
Processing alignment: ref -> stitched_image_S_89.tiff, moving -> stitched_image_S_90.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [13. 10.]
current shift: [13. 10.]
Processing alignment: ref -> stitched_image_S_90.tiff, moving -> stitched_image_S_91.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 4. -5.]
current shift: [ 4. -5.]
Processing alignment: ref -> stitched_image_S_91.tiff, moving -> stitched_image_S_92.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 8. -3.]
current shift: [ 8. -3.]
Processing alignment: ref -> stitched_image_S_92.tiff, moving -> stitched_image_S_93.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 1. -7.]
current shift: [ 1. -7.]
Processing alignment: ref -> stitched_image_S_93.tiff, moving -> stitched_image_S_94.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 3. 14.]
current shift: [ 3. 14.]
Processing alignment: ref -> stitched_image_S_94.tiff, moving -> stitched_image_S_95.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-8. -5.]
current shift: [-8. -5.]
Processing alignment: ref -> stitched_image_S_95.tiff, moving -> stitched_image_S_96.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 7. -6.]
current shift: [ 7. -6.]
Processing alignment: ref -> stitched_image_S_96.tiff, moving -> stitched_image_S_97.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [1. 5.]
current shift: [1. 5.]
Processing alignment: ref -> stitched_image_S_97.tiff, moving -> stitched_image_S_98.tiff
crop pixel shift: [1 0]
Detected pixel offset based on crops (row, col): [ 30. -13.]
current shift: [ 31. -13.]
Processing alignment: ref -> stitched_image_S_98.tiff, moving -> stitched_image_S_99.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ -6. -13.]
current shift: [ -6. -13.]
Processing alignment: ref -> stitched_image_S_99.tiff, moving -> stitched_image_S_100.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [ 3. 36.]
current shift: [ 3. 36.]
Processing alignment: ref -> stitched_image_S_100.tiff, moving -> stitched_image_S_101.tiff
crop pixel shift: [0 0]
Detected pixel offset based on crops (row, col): [-11.  -5.]
current shift: [-11.  -5.]
Processing alignment: ref -> stitched_image_S_101.tiff, moving -> stitched_image_S_102.tiff
crop pixel shift: [2 0]

,moving_path,reference_path,moving_ROI,reference_ROI,current_shift,cumulative_ROI,cumulative_shift,down_scale
0,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(159, 1485, 114, 1007)","(159, 1485, 114, 1007)","[0.0, 0.0]","(159, 1485, 114, 1007)","[0.0, 0.0]",10
1,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(159, 1485, 114, 1007)","[-5.0, 18.0]","(172, 1466, 109, 1009)","[-5.0, 18.0]",10
2,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(154, 1448, 114, 1014)","[-3.0, -12.0]","(160, 1454, 106, 1006)","[-8.0, 6.0]",10
3,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(154, 1448, 114, 1014)","[-3.0, 0.0]","(160, 1454, 103, 1003)","[-11.0, 6.0]",10
4,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(154, 1448, 114, 1014)","[14.0, 6.0]","(166, 1460, 117, 1017)","[3.0, 12.0]",10
...,...,...,...,...,...,...,...,...
111,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1468, 114, 1028)","(156, 1468, 114, 1028)","[0.0, 4.0]","(152, 1464, 154, 1068)","[40.0, -4.0]",10
112,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1468, 114, 1028)","(156, 1468, 114, 1028)","[21.0, -8.0]","(144, 1456, 175, 1089)","[61.0, -12.0]",10
113,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1475, 116, 1027)","(156, 1468, 114, 1028)","[-7.0, -3.0]","(141, 1460, 170, 1081)","[54.0, -15.0]",10
114,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1475, 116, 1027)","(156, 1475, 116, 1027)","[1.0, 7.0]","(148, 1467, 171, 1082)","[55.0, -8.0]",10
115,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1475, 116, 1027)","(156, 1475, 116, 1027)","[13.0, -3.0]","(145, 1464, 184, 1095)","[68.0, -11.0]",10

In [9]:
z_align_df = pd.read_pickle(z_align_df_path)
z_align_df

,moving_path,reference_path,moving_ROI,reference_ROI,current_shift,cumulative_ROI,cumulative_shift,down_scale
0,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(159, 1485, 114, 1007)","(159, 1485, 114, 1007)","[0.0, 0.0]","(159, 1485, 114, 1007)","[0.0, 0.0]",10
1,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(159, 1485, 114, 1007)","[-5.0, 18.0]","(172, 1466, 109, 1009)","[-5.0, 18.0]",10
2,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(154, 1448, 114, 1014)","[-3.0, -12.0]","(160, 1454, 106, 1006)","[-8.0, 6.0]",10
3,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(154, 1448, 114, 1014)","[-3.0, 0.0]","(160, 1454, 103, 1003)","[-11.0, 6.0]",10
4,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(154, 1448, 114, 1014)","(154, 1448, 114, 1014)","[14.0, 6.0]","(166, 1460, 117, 1017)","[3.0, 12.0]",10
...,...,...,...,...,...,...,...,...
111,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1468, 114, 1028)","(156, 1468, 114, 1028)","[0.0, 4.0]","(152, 1464, 154, 1068)","[40.0, -4.0]",10
112,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1468, 114, 1028)","(156, 1468, 114, 1028)","[21.0, -8.0]","(144, 1456, 175, 1089)","[61.0, -12.0]",10
113,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1475, 116, 1027)","(156, 1468, 114, 1028)","[-7.0, -3.0]","(141, 1460, 170, 1081)","[54.0, -15.0]",10
114,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1475, 116, 1027)","(156, 1475, 116, 1027)","[1.0, 7.0]","(148, 1467, 171, 1082)","[55.0, -8.0]",10
115,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_dat...,"(156, 1475, 116, 1027)","(156, 1475, 116, 1027)","[13.0, -3.0]","(145, 1464, 184, 1095)","[68.0, -11.0]",10

In [10]:
use_down_sample = True
zarr_array, zarr_path = apply_alignment(z_align_df, buffer_pixels=20, percentile_low=2.0, percentile_high=99.5, use_down_sample=use_down_sample)

out_pixel_size = pixel_size.copy()

if use_down_sample:
    out_pixel_size['Value'] = pixel_size['Value'] * down_scale
    end_str = "_ds_aligned"
else:
    end_str = "_aligned"

czi_path = zarr_array_to_czi(zarr_path, out_pixel_size, end_str=end_str)

we will downsample during saving of the zarr, this is good during testing for visual inspection
shape of the zarr array to create: (1065, 1396, 116)
creating zarr at: E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_data\session_1115605826\Site 2\Site 2.zarr
Done for idx 0
Done for idx 1
Done for idx 2
Done for idx 3
Done for idx 4
Done for idx 5
Done for idx 6
Done for idx 7
Done for idx 8
Done for idx 9
Done for idx 10
Done for idx 11
Done for idx 12
Done for idx 13
Done for idx 14
Done for idx 15
Done for idx 16
Done for idx 17
Done for idx 18
Done for idx 19
Done for idx 20
Done for idx 21
Done for idx 22
Done for idx 23
Done for idx 24
Done for idx 25
Done for idx 26
Done for idx 27
Done for idx 28
Done for idx 29
Done for idx 30
Done for idx 31
Done for idx 32
Done for idx 33
Done for idx 34
Done for idx 35
Done for idx 36
Done for idx 37
Done for idx 38
Done for idx 39
Done for idx 40
Done for idx 41
Done for idx 42
Done for idx 43
Done for idx 44
Done for idx 45
Done for idx 46
Done for idx 47
Done for idx 48
Done for idx 49
Done for idx 50
Done for idx 51
Done for idx 52
Done for idx 53
Done for idx 54
Done for idx 55
Done for idx 56
Done for idx 57
Done for idx 58
Done for idx 59
Done for idx 60
Done for idx 61
Done for idx 62
Done for idx 63
Done for idx 64
Done for idx 65
Done for idx 66
Done for idx 67
Done for idx 68
Done for idx 69
Done for idx 70
Done for idx 71
Done for idx 72
Done for idx 73
Done for idx 74
Done for idx 75
Done for idx 76
Done for idx 77
Done for idx 78
Done for idx 79
Done for idx 80
Done for idx 81
Done for idx 82
Done for idx 83
Done for idx 84
Done for idx 85
Done for idx 86
Done for idx 87
Done for idx 88
Done for idx 89
Done for idx 90
Done for idx 91
Done for idx 92
Done for idx 93
Done for idx 94
Done for idx 95
Done for idx 96
Done for idx 97
Done for idx 98
Done for idx 99
Done for idx 100
Done for idx 101
Done for idx 102
Done for idx 103
Done for idx 104
Done for idx 105
Done for idx 106
Done for idx 107
Done for idx 108
Done for idx 109
Done for idx 110
Done for idx 111
Done for idx 112
Done for idx 113
Done for idx 114
Done for idx 115
Saving CZI file to: E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_data\session_1115605826\Site 2\Site 2_ds_aligned.czi
Processing frame 0
Processing frame 1
Processing frame 2
Processing frame 3
Processing frame 4
Processing frame 5
Processing frame 6
Processing frame 7
Processing frame 8
Processing frame 9
Processing frame 10
Processing frame 11
Processing frame 12
Processing frame 13
Processing frame 14
Processing frame 15
Processing frame 16
Processing frame 17
Processing frame 18
Processing frame 19
Processing frame 20
Processing frame 21
Processing frame 22
Processing frame 23
Processing frame 24
Processing frame 25
Processing frame 26
Processing frame 27
Processing frame 28
Processing frame 29
Processing frame 30
Processing frame 31
Processing frame 32
Processing frame 33
Processing frame 34
Processing frame 35
Processing frame 36
Processing frame 37
Processing frame 38
Processing frame 39
Processing frame 40
Processing frame 41
Processing frame 42
Processing frame 43
Processing frame 44
Processing frame 45
Processing frame 46
Processing frame 47
Processing frame 48
Processing frame 49
Processing frame 50
Processing frame 51
Processing frame 52
Processing frame 53
Processing frame 54
Processing frame 55
Processing frame 56
Processing frame 57
Processing frame 58
Processing frame 59
Processing frame 60
Processing frame 61
Processing frame 62
Processing frame 63
Processing frame 64
Processing frame 65
Processing frame 66
Processing frame 67
Processing frame 68
Processing frame 69
Processing frame 70
Processing frame 71
Processing frame 72
Processing frame 73
Processing frame 74
Processing frame 75
Processing frame 76
Processing frame 77
Processing frame 78
Processing frame 79
Processing frame 80
Processing frame 81
Processing frame 82
Processing frame 83
Processing frame 84
Processing frame 85
Processing frame 86
Processing frame 87
Processing frame 88
Processing frame 89
Processing frame 90
Processing frame 91
Processing frame 92
Processing frame 93
Processing frame 94
Processing frame 95
Processing frame 96
Processing frame 97
Processing frame 98
Processing frame 99
Processing frame 100
Processing frame 101
Processing frame 102
Processing frame 103
Processing frame 104
Processing frame 105
Processing frame 106
Processing frame 107
Processing frame 108
Processing frame 109
Processing frame 110
Processing frame 111
Processing frame 112
Processing frame 113
Processing frame 114
Processing frame 115

In [14]:
if zarr_path.exists():
  rm_tree(zarr_path)

In [12]:
use_down_sample = False
zarr_array, zarr_path = apply_alignment(z_align_df, buffer_pixels=20, percentile_low=2.0, percentile_high=99.8, use_down_sample=use_down_sample)

doing full scale alignment, it is recomended to check results before with downscale
shape of the zarr array to create: (10290, 13600, 116)
creating zarr at: E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_data\session_1115605826\Site 2\Site 2.zarr
Done for idx 0
Done for idx 1
Done for idx 2
Done for idx 3
Done for idx 4
Done for idx 5
Done for idx 6
Done for idx 7
Done for idx 8
Done for idx 9
Done for idx 10
Done for idx 11
Done for idx 12
Done for idx 13
Done for idx 14
Done for idx 15
Done for idx 16
Done for idx 17
Done for idx 18
Done for idx 19
Done for idx 20
Done for idx 21
Done for idx 22
Done for idx 23
Done for idx 24
Done for idx 25
Done for idx 26
Done for idx 27
Done for idx 28
Done for idx 29
Done for idx 30
Done for idx 31
Done for idx 32
Done for idx 33
Done for idx 34
Done for idx 35
Done for idx 36
Done for idx 37
Done for idx 38
Done for idx 39
Done for idx 40
Done for idx 41
Done for idx 42
Done for idx 43
Done for idx 44
Done for idx 45
Done for idx 46
Done for idx 47
Done for idx 48
Done for idx 49
Done for idx 50
Done for idx 51
Done for idx 52
Done for idx 53
Done for idx 54
Done for idx 55
Done for idx 56
Done for idx 57
Done for idx 58
Done for idx 59
Done for idx 60
Done for idx 61
Done for idx 62
Done for idx 63
Done for idx 64
Done for idx 65
Done for idx 66
Done for idx 67
Done for idx 68
Done for idx 69
Done for idx 70
Done for idx 71
Done for idx 72
Done for idx 73
Done for idx 74
Done for idx 75
Done for idx 76
Done for idx 77
Done for idx 78
Done for idx 79
Done for idx 80
Done for idx 81
Done for idx 82
Done for idx 83
Done for idx 84
Done for idx 85
Done for idx 86
Done for idx 87
Done for idx 88
Done for idx 89
Done for idx 90
Done for idx 91
Done for idx 92
Done for idx 93
Done for idx 94
Done for idx 95
Done for idx 96
Done for idx 97
Done for idx 98
Done for idx 99
Done for idx 100
Done for idx 101
Done for idx 102
Done for idx 103
Done for idx 104
Done for idx 105
Done for idx 106
Done for idx 107
Done for idx 108
Done for idx 109
Done for idx 110
Done for idx 111
Done for idx 112
Done for idx 113
Done for idx 114
Done for idx 115

In [13]:
out_pixel_size = pixel_size.copy()

if use_down_sample:
    out_pixel_size['Value'] = pixel_size['Value'] * down_scale
    end_str = "_ds_aligned"
else:
    end_str = "_aligned"

czi_path = zarr_array_to_czi(zarr_path, out_pixel_size, end_str=end_str)

Saving CZI file to: E:\PROJECTS\EM\Alma\plant2-wafer-1\plant 2_data\session_1115605826\Site 2\Site 2_aligned.czi
Processing frame 0
Processing frame 1
Processing frame 2
Processing frame 3
Processing frame 4
Processing frame 5
Processing frame 6
Processing frame 7
Processing frame 8
Processing frame 9
Processing frame 10
Processing frame 11
Processing frame 12
Processing frame 13
Processing frame 14
Processing frame 15
Processing frame 16
Processing frame 17
Processing frame 18
Processing frame 19
Processing frame 20
Processing frame 21
Processing frame 22
Processing frame 23
Processing frame 24
Processing frame 25
Processing frame 26
Processing frame 27
Processing frame 28
Processing frame 29
Processing frame 30
Processing frame 31
Processing frame 32
Processing frame 33
Processing frame 34
Processing frame 35
Processing frame 36
Processing frame 37
Processing frame 38
Processing frame 39
Processing frame 40
Processing frame 41
Processing frame 42
Processing frame 43
Processing frame 44
Processing frame 45
Processing frame 46
Processing frame 47
Processing frame 48
Processing frame 49
Processing frame 50
Processing frame 51
Processing frame 52
Processing frame 53
Processing frame 54
Processing frame 55
Processing frame 56
Processing frame 57
Processing frame 58
Processing frame 59
Processing frame 60
Processing frame 61
Processing frame 62
Processing frame 63
Processing frame 64
Processing frame 65
Processing frame 66
Processing frame 67
Processing frame 68
Processing frame 69
Processing frame 70
Processing frame 71
Processing frame 72
Processing frame 73
Processing frame 74
Processing frame 75
Processing frame 76
Processing frame 77
Processing frame 78
Processing frame 79
Processing frame 80
Processing frame 81
Processing frame 82
Processing frame 83
Processing frame 84
Processing frame 85
Processing frame 86
Processing frame 87
Processing frame 88
Processing frame 89
Processing frame 90
Processing frame 91
Processing frame 92
Processing frame 93
Processing frame 94
Processing frame 95
Processing frame 96
Processing frame 97
Processing frame 98
Processing frame 99
Processing frame 100
Processing frame 101
Processing frame 102
Processing frame 103
Processing frame 104
Processing frame 105
Processing frame 106
Processing frame 107
Processing frame 108
Processing frame 109
Processing frame 110
Processing frame 111
Processing frame 112
Processing frame 113
Processing frame 114
Processing frame 115